import 'package:uuid/uuid.dart';
import '../models/food_item.dart';

class FoodDatabase {
  static final List<FoodItem> _foods = _buildSampleFoods();
  static final _uuid = Uuid();

  static List<FoodItem> _buildSampleFoods() {
    return [
      FoodItem(
        id: _uuid.v4(),
        name: 'Chicken Breast (Grilled)',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 165,
        protein: 31,
        carbs: 0,
        fat: 3.6,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'White Rice (Cooked)',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 130,
        protein: 2.7,
        carbs: 28,
        fat: 0.3,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Salmon Fillet',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 208,
        protein: 20,
        carbs: 0,
        fat: 13,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Eggs (Scrambled)',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 149,
        protein: 10,
        carbs: 1.6,
        fat: 11,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Avocado',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 160,
        protein: 2,
        carbs: 8.5,
        fat: 14.7,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Banana',
        brand: 'Generic',
        servingSizeG: 100,
        servingSizeLabel: 1,
        servingUnit: 'medium',
        calories: 89,
        protein: 1.1,
        carbs: 23,
        fat: 0.3,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Greek Yogurt',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 59,
        protein: 10,
        carbs: 3.6,
        fat: 0.4,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Oatmeal',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 71,
        protein: 2.5,
        carbs: 12,
        fat: 1.5,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Whole Wheat Bread',
        brand: 'Generic',
        servingSizeG: 100,
        servingSizeLabel: 1,
        servingUnit: 'slice',
        calories: 247,
        protein: 13,
        carbs: 41,
        fat: 3.4,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Peanut Butter',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 588,
        protein: 25,
        carbs: 20,
        fat: 50,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Apple',
        brand: 'Generic',
        servingSizeG: 100,
        servingSizeLabel: 1,
        servingUnit: 'medium',
        calories: 52,
        protein: 0.3,
        carbs: 14,
        fat: 0.2,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Broccoli (Steamed)',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 35,
        protein: 2.4,
        carbs: 7,
        fat: 0.4,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Sweet Potato (Baked)',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 86,
        protein: 1.6,
        carbs: 20,
        fat: 0.1,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Ground Beef (90% Lean)',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 215,
        protein: 26,
        carbs: 0,
        fat: 12,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Pasta (Cooked)',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 131,
        protein: 5,
        carbs: 25,
        fat: 1.1,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Almonds',
        brand: 'Generic',
        servingSizeG: 100,
        servingSizeLabel: 28,
        servingUnit: 'g (handful)',
        calories: 579,
        protein: 21,
        carbs: 22,
        fat: 50,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Tuna (Canned in Water)',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 116,
        protein: 26,
        carbs: 0,
        fat: 0.8,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Milk (Whole)',
        brand: 'Generic',
        servingSizeG: 100,
        servingSizeLabel: 244,
        servingUnit: 'ml (1 cup)',
        calories: 61,
        protein: 3.2,
        carbs: 4.8,
        fat: 3.3,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Cheddar Cheese',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 403,
        protein: 25,
        carbs: 1.3,
        fat: 33,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Mixed Green Salad',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 17,
        protein: 1.2,
        carbs: 3.3,
        fat: 0.2,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Whey Protein Shake',
        brand: 'Generic',
        servingSizeG: 30,
        servingSizeLabel: 1,
        servingUnit: 'scoop',
        calories: 120,
        protein: 24,
        carbs: 3,
        fat: 1.5,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Quinoa (Cooked)',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 120,
        protein: 4.4,
        carbs: 21,
        fat: 1.9,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Cottage Cheese',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 98,
        protein: 11,
        carbs: 3.4,
        fat: 4.3,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Turkey Breast (Deli)',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 104,
        protein: 22,
        carbs: 1.5,
        fat: 1.2,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Olive Oil',
        brand: 'Generic',
        servingSizeG: 15,
        servingSizeLabel: 1,
        servingUnit: 'tbsp',
        calories: 119,
        protein: 0,
        carbs: 0,
        fat: 13.5,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Brown Rice (Cooked)',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 111,
        protein: 2.6,
        carbs: 23,
        fat: 0.9,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Dark Chocolate (70%)',
        brand: 'Generic',
        servingSizeG: 100,
        servingSizeLabel: 30,
        servingUnit: 'g (2 squares)',
        calories: 598,
        protein: 7.8,
        carbs: 46,
        fat: 43,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Strawberries',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 32,
        protein: 0.7,
        carbs: 8,
        fat: 0.3,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Tofu (Firm)',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 76,
        protein: 8,
        carbs: 1.9,
        fat: 4.8,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Hummus',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 166,
        protein: 7.9,
        carbs: 14,
        fat: 9.6,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Beef Steak (Sirloin)',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 206,
        protein: 26,
        carbs: 0,
        fat: 11,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Orange',
        brand: 'Generic',
        servingSizeG: 100,
        servingSizeLabel: 1,
        servingUnit: 'medium',
        calories: 47,
        protein: 0.9,
        carbs: 12,
        fat: 0.1,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Blueberries',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 57,
        protein: 0.7,
        carbs: 14,
        fat: 0.3,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Edamame (Steamed)',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 121,
        protein: 12,
        carbs: 8.9,
        fat: 5.2,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Sourdough Bread',
        brand: 'Generic',
        servingSizeG: 100,
        servingSizeLabel: 1,
        servingUnit: 'slice',
        calories: 266,
        protein: 9.2,
        carbs: 49,
        fat: 3.1,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Chickpeas (Canned)',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 139,
        protein: 7.2,
        carbs: 23,
        fat: 2.6,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Mozzarella (Fresh)',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 280,
        protein: 22,
        carbs: 3.1,
        fat: 20,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Trail Mix',
        brand: 'Generic',
        servingSizeG: 100,
        servingSizeLabel: 40,
        servingUnit: 'g (handful)',
        calories: 462,
        protein: 12,
        carbs: 44,
        fat: 29,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Green Smoothie',
        brand: 'Generic',
        servingSizeG: 100,
        servingSizeLabel: 360,
        servingUnit: 'ml (1.5 cup)',
        calories: 39,
        protein: 1.5,
        carbs: 8,
        fat: 0.5,
      ),
      FoodItem(
        id: _uuid.v4(),
        name: 'Shrimp (Grilled)',
        brand: 'Generic',
        servingSizeG: 100,
        calories: 99,
        protein: 24,
        carbs: 0.2,
        fat: 0.3,
      ),
    ];
  }

  static List<FoodItem> get allFoods => List.unmodifiable(_foods);

  static List<FoodItem> searchFoods(String query) {
    if (query.isEmpty) return _foods;
    final q = query.toLowerCase();
    return _foods
        .where((f) => f.name.toLowerCase().contains(q))
        .toList();
  }

  static List<FoodItem> getFavorites() {
    return _foods.where((f) => f.isFavorite).toList();
  }

  static void addFood(FoodItem food) {
    _foods.add(food);
  }

  static void toggleFavorite(String foodId) {
    final index = _foods.indexWhere((f) => f.id == foodId);
    if (index != -1) {
      _foods[index] = _foods[index].copyWith(
        isFavorite: !_foods[index].isFavorite,
      );
    }
  }
}
